[env]
platform = ch32v
build_flags = -I. -D DEBUG
framework = noneos-sdk
upload_protocol = isp
extra_scripts =
    pre:git_version.py

[env:genericCH32X035G8U6]
board = genericCH32X035G8U6
;turn off the compilation of the built-in debug implementation
board_build.use_builtin_debug_code = no
